version: '3'
services:
  strapi:
    image: strapi/strapi:latest
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./strapi:/srv/app
    ports:
      - 1337:1337
    networks:
      - docker-3_db-lan

networks:
  postgresql_db-lan:
    external: true